# .github/workflows/fetch.yml

name: Merge upstream branches
on:
  schedule:
    - cron: 0 0 * * 1
  workflow_dispatch:
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge upstream
        run: |
          git config --global user.name 'tianlong.jiang'
          git config --global user.email 'tianlong.jiang@outlook.com'
          git config --global credential.helper store
          git clone https://github.com/tianlongJ/Scoop.git tmp
          cd tmp
          git remote add upstream  https://github.com/ScoopInstaller/Scoop.git
          git fetch upstream
          git merge upstream/master
          git push origin master
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
